### ISSUE TITLE
panic - connection reset by peer

### ISSUE THREAD

**Issue by hausschwein** [chr-fritz/fritzbox_exporter#4]
I have the fritzbox_exporter installed on my raspberrypi, but when I try to run the fritzbox_exporter -test I get the following error message:

$GOPATH/bin/fritzbox_exporter -test
panic: Get http://fritz.box:49000/igddesc.xml: read tcp [xxxxxxxxxx]:36102->[xxxxxxxxxx]:49000: read: connection reset by peer

goroutine 1 [running]:
main.test()
        /root/go/src/github.com/ndecker/fritzbox_exporter/main.go:285 +0x33c
main.main()
        /root/go/src/github.com/ndecker/fritzbox_exporter/main.go:312 +0x204

On my fritzbox I have enabled the "Statusinformationen über UPnP übertragen" enabled.

How can I solve this problem?

**Comment by chr-fritz** [comment]
Hi,

obviously you tried to run a version from a different fork than mine. Could you please try it with my fork or post this issue to that fork you are using.

Thank you.
